ARG BUILD_FROM
ARG BUILD_ARCH
ARG BUILD_VERSION

# Utilisation de BUILD_FROM comme image de base standard
# Le superviseur HA s'assure que ${BUILD_FROM} contient déjà le bon tag d'architecture (e.g., :aarch64)
# On retire la syntaxe --platform=linux/${BUILD_ARCH} qui causait l'erreur.
FROM ${BUILD_FROM}

# Install necessary dependencies, y compris Firefox ESR
# Xorg et dépendances d'entrée
RUN apk update && apk add --no-cache \
    xorg-server \
    xf86-video-modesetting \
    xf86-input-libinput \
    libinput \
    udev \
    libinput-udev \
    libevdev \
    mesa-dri-gallium \
    mesa-egl \
    mesa-gles \
    libdrm \
    libxkbcommon \
    ttf-dejavu \
    util-linux \
    xdotool \
    xinput \
    xrandr \
    xset \
    unclutter-xfixes \
    setxkbmap \
    openbox \
    onboard \
    py3-pip \
    python3-tkinter \
    patch \
    bash \
    # CORRECTION : Installation de Firefox ESR
    firefox-esr \
    nss \
    # Nettoyage
    && rm -rf /var/cache/apk/*

# Set the display variable
ENV DISPLAY=:0

# Copy over 'xorg.conf.default' and other configuration files
COPY xorg.conf.default /etc/X11/
COPY translations/*.yaml /translations/

# Nous gardons le COPY de userconf.lua commenté pour référence, mais il est ignoré
# COPY userconf.lua /root/.config/lutumba/

COPY run.sh /
RUN chmod a+x /run.sh

COPY rest_server.py /
COPY toggle_keyboard.py /

# Install python dependencies
RUN pip3 install aiohttp

# Create log directory and change permissions for files
RUN mkdir -p /var/log/supervisor && \
    chmod a+rwx /var/log/supervisor && \
    chmod a+x /run.sh && \
    chmod a+x /rest_server.py && \
    chmod a+x /toggle_keyboard.py

# Final command
CMD ["/run.sh"]
